# Site settings
title: Benjo Kho
description: "My Personal Blog"
#baseurl: "/space-jekyll-template" # the subpath of your site, e.g. /blog
url: "http://benjokho.github.io"

# User settings
username: benjokho
user_title: Benjo Kho
email: benjokho@gmail.com
facebook_username: benjokho
twitter_username: benjokho
github_username:  benjokho

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: About me
    url: /about
# projects in header index
projects:
  - name: nature-photography-website
    url: https://github.com/benjokho/nature-photography-website
  - name: nine-by-nine
    url: https://github.com/benjokho/nine-by-nine
  - name: anki-note-maker
    url: https://github.com/benjokho/anki-note-maker
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
